package Presentacion;
import Entidades.Usuario;
import Util.RecordatorioSistema;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;

public class DashboardForm extends javax.swing.JFrame {
    private RecordatorioSistema sistemaRecordatorios;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardForm.class.getName());
    private Usuario usuario;
    private static DashboardForm instanciaActual;

    public DashboardForm() {
        initComponents();
    }
    public DashboardForm(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        lblBienvenida.setText("Hola, " + usuario.getNombre()); 
        instanciaActual = this;
         
        inicializarPanelTareas();
        inicializarCalendario();
        inicializarPanelSemanal(); 
        inicializarPanelRecordatorios(); 
        iniciarSistemaRecordatorios(); 
        this.setLocationRelativeTo(null);
    }
    
    private void inicializarPanelTareas() {
        PanelTareas.removeAll();
        PanelTareas panelTareas = new PanelTareas(usuario);
        PanelTareas.setLayout(new BorderLayout());
        PanelTareas.add(panelTareas, BorderLayout.CENTER);
        PanelTareas.revalidate();
        PanelTareas.repaint();
    }
    
    public static void actualizarPaneles() {
        if (instanciaActual != null) {
            instanciaActual.refrescarTodosLosPaneles();
        }
    }
    private void inicializarPanelRecordatorios() {
        PanelRecordatorios.removeAll();
        PanelRecordatorios panelRecordatorios = new PanelRecordatorios(usuario.getUsuarioID());
        PanelRecordatorios.setLayout(new BorderLayout());
        PanelRecordatorios.add(panelRecordatorios, BorderLayout.CENTER);
        PanelRecordatorios.revalidate();
        PanelRecordatorios.repaint();
    }
    
    private void iniciarSistemaRecordatorios() {
        sistemaRecordatorios = new RecordatorioSistema();
        sistemaRecordatorios.iniciarSistema();
    }
    
    // Método para cerrar correctamente
    @Override
    public void dispose() {
        if (sistemaRecordatorios != null) {
            sistemaRecordatorios.detenerSistema();
        }
        super.dispose();
    }
    
    private void inicializarCalendario() {
        // Limpiar el panel del calendario si ya tiene contenido
        PanelCalendario.removeAll();

        // Crear y agregar el calendario personalizado
        CalendarioPanel calendario = new CalendarioPanel(usuario.getUsuarioID());
        PanelCalendario.setLayout(new BorderLayout());
        PanelCalendario.add(calendario, BorderLayout.CENTER);

        // Actualizar la interfaz
        PanelCalendario.revalidate();
        PanelCalendario.repaint();
    }
    
    public void refrescarTodosLosPaneles() {
        inicializarPanelTareas();
        inicializarCalendario();
        inicializarPanelSemanal();
        inicializarPanelRecordatorios(); 
    }
    
    private void inicializarPanelSemanal() {
        // Limpiar el panel de la semana si ya tiene contenido
        PanelSemana.removeAll();

        // Crear y agregar el panel semanal
        PanelSemanal panelSemanal = new PanelSemanal(usuario.getUsuarioID());
        PanelSemana.setLayout(new BorderLayout());
        PanelSemana.add(panelSemanal, BorderLayout.CENTER);

        // Actualizar la interfaz
        PanelSemana.revalidate();
        PanelSemana.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelCalendario = new javax.swing.JPanel();
        PanelSemana = new javax.swing.JPanel();
        PanelTareas = new javax.swing.JPanel();
        PanelRecordatorios = new javax.swing.JPanel();
        PanelCerrarSesion = new javax.swing.JPanel();
        lblBienvenida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane1.setBackground(new java.awt.Color(255, 153, 153));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane1.setFont(new java.awt.Font("Swis721 Cn BT", 1, 12)); // NOI18N
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        PanelCalendario.setBackground(new java.awt.Color(255, 255, 255));
        PanelCalendario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout PanelCalendarioLayout = new javax.swing.GroupLayout(PanelCalendario);
        PanelCalendario.setLayout(PanelCalendarioLayout);
        PanelCalendarioLayout.setHorizontalGroup(
            PanelCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 911, Short.MAX_VALUE)
        );
        PanelCalendarioLayout.setVerticalGroup(
            PanelCalendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("CALENDARIO", PanelCalendario);

        PanelSemana.setBackground(new java.awt.Color(255, 255, 255));
        PanelSemana.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout PanelSemanaLayout = new javax.swing.GroupLayout(PanelSemana);
        PanelSemana.setLayout(PanelSemanaLayout);
        PanelSemanaLayout.setHorizontalGroup(
            PanelSemanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 911, Short.MAX_VALUE)
        );
        PanelSemanaLayout.setVerticalGroup(
            PanelSemanaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("SEMANA", PanelSemana);

        PanelTareas.setBackground(new java.awt.Color(255, 255, 255));
        PanelTareas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout PanelTareasLayout = new javax.swing.GroupLayout(PanelTareas);
        PanelTareas.setLayout(PanelTareasLayout);
        PanelTareasLayout.setHorizontalGroup(
            PanelTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 911, Short.MAX_VALUE)
        );
        PanelTareasLayout.setVerticalGroup(
            PanelTareasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("TAREAS", PanelTareas);

        PanelRecordatorios.setBackground(new java.awt.Color(255, 255, 255));
        PanelRecordatorios.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout PanelRecordatoriosLayout = new javax.swing.GroupLayout(PanelRecordatorios);
        PanelRecordatorios.setLayout(PanelRecordatoriosLayout);
        PanelRecordatoriosLayout.setHorizontalGroup(
            PanelRecordatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 911, Short.MAX_VALUE)
        );
        PanelRecordatoriosLayout.setVerticalGroup(
            PanelRecordatoriosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 574, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("RECORDATORIOS", PanelRecordatorios);

        PanelCerrarSesion.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelCerrarSesionLayout = new javax.swing.GroupLayout(PanelCerrarSesion);
        PanelCerrarSesion.setLayout(PanelCerrarSesionLayout);
        PanelCerrarSesionLayout.setHorizontalGroup(
            PanelCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 915, Short.MAX_VALUE)
        );
        PanelCerrarSesionLayout.setVerticalGroup(
            PanelCerrarSesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 578, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("CERRAR SESIÓN", PanelCerrarSesion);

        lblBienvenida.setFont(new java.awt.Font("Roboto SemiBold", 1, 12)); // NOI18N
        lblBienvenida.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lblBienvenida))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1033, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblBienvenida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        int index = jTabbedPane1.getSelectedIndex();

        // Verificar si el tab seleccionado es el que contiene PanelCerrarSesion
        if (jTabbedPane1.getComponentAt(index) == PanelCerrarSesion) {
            int opcion = JOptionPane.showConfirmDialog(
                this,
                "Esta seguro que desea cerrar sesion?",
                "Confirmar cierre de sesion",
                JOptionPane.YES_NO_OPTION
            );

            if (opcion == JOptionPane.YES_OPTION) {
                dispose();
                new LoginForm().setVisible(true);
            } else {

                jTabbedPane1.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_jTabbedPane1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DashboardForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelCalendario;
    private javax.swing.JPanel PanelCerrarSesion;
    private javax.swing.JPanel PanelRecordatorios;
    private javax.swing.JPanel PanelSemana;
    private javax.swing.JPanel PanelTareas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblBienvenida;
    // End of variables declaration//GEN-END:variables
}
